services:
  db:
    image: postgres:15-alpine
    container_name: sigma_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "1234:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./SigmaElectronix.Server
      dockerfile: Dockerfile
    container_name: sigma_backend
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTP_PORTS: 8080
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=sigma_db;Username=db_user;Password=db_password"
    restart: unless-stopped

  frontend:
    build:
      context: ./sigmaelectronix.client
      dockerfile: Dockerfile
    container_name: sigma_frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: unless-stopped